Belajar Numpy

Numpy adalah pustaka python open source yang digunakan hampir disemua bidang data science. Numpy digunakan untuk melakukan operasi matematika, dapat dikolaborasikan dengan libbrary lain. Pada intinya Numpay dapat membuat multidimensi list atau matriks

1. cara Menginstal Numpy
#pip install numpy

In [1]:
import numpy
print(numpy.__version__)

1.26.4


basic dari numpy adalah array. Array itu apa?

Array

In [4]:
import numpy as np #kolom sudah aktif dan berjalan

In [6]:
#untuk membuat kita menggunakan np.array()
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
#array isinya 0 sebanyak 5
b = np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#array isinya 1 sebanyak 5 kali
c = np.ones(10)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
#array kosong np.empty

In [14]:
#(start, stop, step)
#for i in range(1, 11, 2) (start, stop-1)
#arange (start, stop, step)
d = np.arange(4)
d

array([0, 1, 2, 3])

In [16]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

tambah array, Hapus array, dan mengurutkan Array

menambahkan data kedalam Array

In [22]:
#np.append()
array2 = np.array([1,34,2,7,8,20,3,5,7,32])
np.append(array2,[5,10,100])

array([  1,  34,   2,   7,   8,  20,   3,   5,   7,  32,   5,  10, 100])

In [14]:
array1 = np.array([3,4,7,9,18,7,26,89])
array1 = np.append(array1,[10,101,10])
array1

array([  3,   4,   7,   9,  18,   7,  26,  89,  10, 101,  10])

Remove

In [15]:
array1

array([  3,   4,   7,   9,  18,   7,  26,  89,  10, 101,  10])

In [18]:
array1_hapus = np.delete(array1,1)
array1_hapus

array([  3,   7,   9,  18,   7,  26,  89,  10, 101,  10])

sort

In [19]:
array2

array([ 1, 34,  2,  7,  8, 20,  3,  5,  7, 32])

In [20]:
np.sort(array2)

array([ 1,  2,  3,  5,  7,  7,  8, 20, 32, 34])

array 2Dimensi

In [21]:
#ciri khas dari dimensi
#satu dimensi
array_baru = np.array([2,3,4,5,6,7])
array_baru

array([2, 3, 4, 5, 6, 7])

In [44]:
#dua dimensi
array_2d = np.array([[1,2,3,3], ##baris 0
                     [4,5,6,0], ##baris 1 
                     [4,6,7,8], ##baris 2
                     [11,10,8,6] ##baris 3
                    ])
array_2d

array([[ 1,  2,  3,  3],
       [ 4,  5,  6,  0],
       [ 4,  6,  7,  8],
       [11, 10,  8,  6]])

In [46]:
#mau mengakses ROW/ Baris
array_2d[3]

array([11, 10,  8,  6])

In [47]:
#mau mengakses baris dan kolom
array_2d[2,2]

7

In [48]:
#mau mengakses kolom 
array_2d[:,2]

array([3, 6, 7, 8])

In [49]:
#mau mengakses kolom
array_2d[:,[0,2]]

array([[ 1,  3],
       [ 4,  6],
       [ 4,  7],
       [11,  8]])

ini untuk reshape

In [24]:
d = np.arange(6)
d #1 baris 6 kolom

array([0, 1, 2, 3, 4, 5])

In [26]:
d_reshape = d.reshape(3,2)
d_reshape

array([[0, 1],
       [2, 3],
       [4, 5]])

#tugas mini quiz

#buatlah array yang berisikan nilai 1-1000 dengan step bernilai 10

#2. buatlah array yang berisikan bilangan genap dari 0-10, lalu tambahkan nilai 100 didalam listnya

#3. buatlah array bernilai 0 sebanyak 20 kali

In [37]:
f = np.arange(1, 1001, 10)
f

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121,
       131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251,
       261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381,
       391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491, 501, 511,
       521, 531, 541, 551, 561, 571, 581, 591, 601, 611, 621, 631, 641,
       651, 661, 671, 681, 691, 701, 711, 721, 731, 741, 751, 761, 771,
       781, 791, 801, 811, 821, 831, 841, 851, 861, 871, 881, 891, 901,
       911, 921, 931, 941, 951, 961, 971, 981, 991])

In [34]:
g =  np.arange(0, 11, 2)
g

array([ 0,  2,  4,  6,  8, 10])

In [36]:
h = np.zeros(20)
h

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

indexing dan slicing

In [39]:
array3 = np.array([1,2,3,4,12,5,6,7,8,9,32,2,3,5])
array3

array([ 1,  2,  3,  4, 12,  5,  6,  7,  8,  9, 32,  2,  3,  5])

In [40]:
print(array3[:-1])

[ 1  2  3  4 12  5  6  7  8  9 32  2  3]


In [41]:
kata = "Python"
print(kata[::-1])

nohtyP


In [54]:
#miniquiz 2 slicing dan akses mini data
array_miniQuiz = np.array([[6,12,32,42],
                          [2,232,12,23],
                          [41,22,13,24],
                          [111,210,42,34]
                          ])
array_miniQuiz

#1. tolong berikan berikan ouput dengan mengakses kolom 2 dan 3
#2. tolong berikan output dengan mengakses baris 2 dengan elemen data ke 1
#3. tolong berikan output dengan mengakses baris 1 dan 2

#miniquiz slicing
#1. aku punya kata "NGODING' ---> DING
#2. aku punya kata "Kereta" ----> RETA
#3. aku punya kata "JAUH" ----> huaj



array([[  6,  12,  32,  42],
       [  2, 232,  12,  23],
       [ 41,  22,  13,  24],
       [111, 210,  42,  34]])

In [58]:
array_miniQuiz[:,[1,3]]

array([[ 12,  42],
       [232,  23],
       [ 22,  24],
       [210,  34]])

In [59]:
array_miniQuiz[1,0]

2

In [61]:
array_miniQuiz[[0,1]]

array([[  6,  12,  32,  42],
       [  2, 232,  12,  23]])

In [66]:
j= "NGODING"
print(j[3:7])

DING


In [68]:
k= "Kereta"
print(k[2:6].upper())

RETA


In [27]:
l= "JAUH"
print(l[::-1].lower())

huaj


In [35]:
#mengecek dimensi

array_example = np.array([[9,8,5,4],
                          [10,11,12,13],
                          [6,8,7,4],
                          [2,3,4,5]])
array_example

array([[ 9,  8,  5,  4],
       [10, 11, 12, 13],
       [ 6,  8,  7,  4],
       [ 2,  3,  4,  5]])

In [31]:
array_example.ndim #berapa dimensi didalam array

2

In [33]:
sample_array = np.array([1,2,3,4])
sample_array.ndim

1

In [37]:
#mengscek ukuran data(menghitung total keseluruhan data) mirip dengan fungsi len()
array_example.size

16

In [41]:
sample_array.size

4

In [45]:
array_example.shape #(mengetahui jumlah baris (digit 1) dan kolom(digit2)


(4, 4)

In [47]:
#reshape (menyusun ulang), 
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [53]:
b = a.reshape(3,2)
print(b.shape)
b

(3, 2)


array([[0, 1],
       [2, 3],
       [4, 5]])

In [55]:
c = a.reshape(2,3)
print(c.shape)
c

(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
d = a.reshape(6,1)
print(d.shape)
print(d)

(6, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [61]:
#convert 1D to 2D, 2D to 1D

print(a.shape)
print(a)

(6,)
[0 1 2 3 4 5]


In [65]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2.ndim)
print(a2)

(1, 6)
2
[[0 1 2 3 4 5]]


In [75]:
array_example2 = array_example.flatten()
array_example2

array([ 9,  8,  5,  4, 10, 11, 12, 13,  6,  8,  7,  4,  2,  3,  4,  5])

In [77]:
array_example.shape

(4, 4)

In [79]:
array_example2.shape

(16,)

In [81]:
#logical Numpy
array_example

array([[ 9,  8,  5,  4],
       [10, 11, 12, 13],
       [ 6,  8,  7,  4],
       [ 2,  3,  4,  5]])

In [83]:
array_example > 7

array([[ True,  True, False, False],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [False, False, False, False]])

In [87]:
array_example[array_example>7]

array([ 9,  8, 10, 11, 12, 13,  8])

In [89]:
array_example[array_example>7].ndim

1

In [91]:
array_example[array_example>7].shape

(7,)

In [93]:
array_example[array_example>7].size

7

In [105]:
d = np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
#bilangan di modulo 2 sisanya adalah 0
#2%2 --> 0 genap, 4%2 --> 0, genap, 5%2 --> 1 ganjil.

bilangan_genap = (d%2 == 0)
print(d[bilangan_genap])

[0 2 4 6 8]


In [113]:
# d > 2 dan d < 11
# 12 < age < 15
#operator and (&)
double_logic = d[(d>2) & (d<11)]
double_logic

array([3, 4, 5, 6, 7, 8, 9])

In [115]:
double_logic2 = d[(d>2) | (d<11)]
double_logic2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a = -2
#if (a<1) and (a >- 3) #True or False
#if (a>2) or (a <- 3) #True or False
print ((a<1) and (a >- 3))
print ((a>2) or (a <- 3))


True
False


In [127]:
#creating array from existing data
# .view() ---> gunanya untuk menampilkan atau show dari data yang sudah tersedia. ingat SHOW tidak berfungsi untuk mengcopy data

e = np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
tampil_e = e.view()
tampil_e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
# .copy() --> gunanya untuk menyalin data dari pusat yang disimpan kedalan variabel baru

tampil_ecopy = e.copy()
tampil_ecopy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
vstack, hstack, hsplit

In [134]:
a_1 = np.array([[1,1],[2,2]])
a_1

array([[1, 1],
       [2, 2]])

In [138]:
a_2 = np.array([[5,6],[7,8]])
a_2

array([[5, 6],
       [7, 8]])

In [162]:
#vstack --> menggabungkan 2 array menjado satu dengan susunan vertikal
result_vstack = np.vstack((a_1,a_2))
result_vstack

array([[1, 1],
       [2, 2],
       [5, 6],
       [7, 8]])

In [164]:
result_vstack.shape

(4, 2)

In [171]:
#hstack digunakan untuk menggabungkan 2 array secara horizontal
#arr_1 = [[1,1],[2,2]]
#arr_2 = [[5,6],[7,8]]
#--> hstack output [ [ 1,1,5,6],
                    #[2,2,7,8]
#]

result_hstack = np.hstack((a_1,a_2))
result_hstack


array([[1, 1, 5, 6],
       [2, 2, 7, 8]])

In [187]:
#operator matematika numpy
bilangan1 = np.array([8,2,3])
bilangan2 = np.array([10,2,3])

#pertambahan
result = bilangan1 + bilangan2
result

array([18,  4,  6])

In [189]:
result_penguranga = bilangan1 - bilangan2
result_penguranga

array([-2,  0,  0])

In [191]:
result_pengkalian = bilangan1 * bilangan2
result_pengkalian

array([80,  4,  9])

In [193]:
#pembagian
result_pembagian = bilangan1 // bilangan2
result_pembagian

array([0, 1, 1])

1. soal reshape
array disimpan di variabel z bilanagan 1-100 dengan kelipatan 5,
ubahlah dari 1D ke 2D,
ubah jadi 2 baris

3. soal vstack dan hstack,
array1 = [5,6,7,4,2,3,4,10],
array2 = [7,8,6,5,4,3,2,10]

vstack -->
5 6
7 4
2 3
4 10

hstack -->
5 6 7 4 7 8 6 5
2 3 4 10 4 3 2 10

In [202]:
array_soal = np.arange(1, 101, 5)
print(array_soal)
print(array_soal.shape)


[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
(20,)


In [204]:
array_soal_reshape =  array_soal.reshape(2,10)
array_soal_reshape

array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71, 76, 81, 86, 91, 96]])

In [208]:
array1 = [5,6,7,4,2,3,4,10]
array2 = [7,8,6,5,4,3,2,10]

soal_vstack = np.vstack((array1, array2))
soal_vstack

array([[ 5,  6,  7,  4,  2,  3,  4, 10],
       [ 7,  8,  6,  5,  4,  3,  2, 10]])

In [210]:
soal_hstack = np.hstack((array1, array2))
soal_hstack

array([ 5,  6,  7,  4,  2,  3,  4, 10,  7,  8,  6,  5,  4,  3,  2, 10])